### PR TITLE
Improved to directly access to relations without SQL executions.

### PR DESCRIPTION
**Pull request by s-hironobu**
I modified pg_plan_advsr to directly access to relations such as plan_repo.plan_history, hint_plan.hints, etc, without SQL executions internally.

By this modification, users do not need to set the environment variables: PGHOST, PGPORT, PGDATABASE, and PGUSER.

The biggest improvement is that  users can create and run this extension on any database.

### CODE REVIEW

**Comment by yamatattsu** [comment]
Hi Suzuki-san,

Thanks for sending the pull request!
Finally, I checked it and found some miner problems.
The comments are following, I'm happy if you revise it. :)

1) deleteHints() 
  It always return "false" because the variable ret doesn't change from false. 
  Therefore, the extension emits "delete error: hint_plan.hints" many times, unfortunately.
  I guess that to replace "bool ret = false" with "bool ret = true" is fine. Right? :)

```
deleteHints()
{
    bool ret = false;
    ...
    return ret;
}
```

2) Coding styles
  You can use pg_indent to fix the style because using PostgreSQL coding style for 
  consistency is good. 
  For examples:
    - Using Tab is preferable than white spaces as possible. (set tabstop=4 on vi, if you used vi)
    - While keyword and left parenthesis would be same indent level like this:

```
    while (....)
    {
```

Thanks,
Tatsuro Yamada

**Comment by s-hironobu** [comment]
I fixed the bug. After committed, I'll make a new patch to reformat by pgindent.

**Comment by yamatattsu** [comment]
Thanks!! :-D

**Comment by yamatattsu** [comment]
Hi Suzuki-san,

Oops, I got SIGSEGV unfortunately. 
I tested the extension on PG108. 

My repro is the following:

      truncate hint_plan.hints;
      truncate plan_repo.plan_history;
      truncate plan_repo.norm_queries;
      truncate plan_repo.raw_queries;
      drop extension pg_hint_plan;
      create extension pg_hint_plan;

      set pg_hint_plan.enable_hint_table to on;
      explain analyze select count(*) from pg_stat_user_indexes;



Do you have any ideas to solve it?


	Program received signal SIGSEGV, Segmentation fault.
	0x000000000047e928 in heap_compute_data_size (tupleDesc=0x7fe664152110, values=0x7ffd256fe600, isnull=0x7ffd256fe5f0 "")
	    at heaptuple.c:106
	106                             VARATT_CAN_MAKE_SHORT(DatumGetPointer(val)))
	(gdb) bt
	#0  0x000000000047e928 in heap_compute_data_size (tupleDesc=0x7fe664152110, values=0x7ffd256fe600, isnull=0x7ffd256fe5f0 "")
	    at heaptuple.c:106
	#1  0x000000000048063a in heap_form_tuple (tupleDescriptor=0x7fe664152110, values=0x7ffd256fe600, isnull=0x7ffd256fe5f0 "")
	    at heaptuple.c:736
	#2  0x00007fe65c9d7bc7 in insertPlanHistory (norm_query_hash=0x7ffd256fe6d0 "bcd2a18d343f23baec6302cff27d99f6",
	    pgsp_queryid=2765168183, pgsp_planid=3376735346, execution_time=10.925498000000001,
	    rows_hint=0x2d48848 "ROWS(c x i n #46) \nROWS(c x n #46) \nROWS(c n #25) ",
	    scan_hint=0x2d45508 "SEQSCAN(x) SEQSCAN(c) SEQSCAN(n) INDEXSCAN(i) ",
	    join_hint=0x2d483f8 "NESTLOOP(c x i n) \nHASHJOIN(c x n) \nHASHJOIN(c n) ", lead_hint=0x2d50b40 "LEADING( ((x (c n ))i ) )",
	    diff_of_joins=75, join_cnt=3, application_name=0x2d646a8 "psql") at pg_plan_advsr.c:364
	#3  0x00007fe65c9da20a in store_info_to_tables (totaltime=10.925498000000001,
	    sourcetext=0x2bf50f0 "explain analyze select * from pg_stat_user_indexes;") at pg_plan_advsr.c:1515
	#4  0x00007fe65c9da03b in pg_plan_advsr_ExplainPrintPlan (es=0x2d482b8, queryDesc=0x2cce330) at pg_plan_advsr.c:1474

**Comment by s-hironobu** [comment]
Um... I tested PG10.9 on CentOS 7.2 (on Vagrant@OSX), but this extension worked without trouble.

**Comment by yamatattsu** [comment]
Hi Suzuki-san,

As I created my new environment and tested it again,
It works fine on PG108 and PG109. :-D
I guessed my trouble caused by my development environment.
Sorry for taking your time.

I realized we need the following things to get stability.
Regression tests
Easy install script to avoid a mistake creating an environment :(
I'm going to consider creating Regression tests, firstly.

Cheers!
Tatsuro Yamada

**Pull request merged**
